default_connection_name = "ga_dev_keypair_auth"

[cli.features]
enable_snowflake_projects = true

[connections.ga_dev_keypair_auth]
authenticator = "SNOWFLAKE_JWT"
user = "ga_dev"
role = "github_action_dev"
